# Generated by Django 5.1.2 on 2024-10-24 18:39

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=50, verbose_name='nome')),
                ('fone', models.CharField(help_text='Numero de Telefone', max_length=15, verbose_name='fone')),
                ('email', models.EmailField(help_text='Endereço de E-mail', max_length=100, unique=True, verbose_name='E-mail')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='pessoas', variations={}, verbose_name='Foto')),
                ('idade', models.IntegerField(help_text='Idade', max_length=50, verbose_name='Idade')),
                ('Hrs', models.CharField(help_text='Horas de Trabalho', max_length=100, verbose_name='Horas')),
            ],
            options={
                'verbose_name': 'Horas',
                'verbose_name_plural': 'Horas de Trabalho Pro dia',
            },
        ),
    ]
