# Generated by Django 5.1.2 on 2024-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='idade',
            field=models.IntegerField(help_text='Idade', verbose_name='Idade'),
        ),
    ]
