# Generated by Django 5.1.2 on 2024-10-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_funcionario_idade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='Hrs',
            new_name='hrs',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(default=1, help_text='Função na empresa', max_length=35, verbose_name='Função'),
            preserve_default=False,
        ),
    ]
