# Generated by Django 5.1.2 on 2024-11-07 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('vitima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.DecimalField(decimal_places=2, help_text='unidade de items do chamado', max_digits=5, verbose_name='unidade')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='quantidade do produtos em estoque', max_digits=5, verbose_name='Quantidade')),
                ('prioridade', models.CharField(choices=[('A', 'ALTA'), ('M', 'MEDIA'), ('B', 'BAIXA')], help_text='Prioridade do chamado', max_length=1, verbose_name='prioridade')),
                ('status', models.CharField(default='Em andamento', help_text='Status do chamado', max_length=1, verbose_name='Status')),
                ('descricao', models.TextField(help_text='Descricao do chamado', max_length=500, verbose_name='Descricao')),
                ('funcionario', models.ForeignKey(help_text='Nome do funcionario', on_delete=django.db.models.deletion.PROTECT, to='funcionario.funcionario', verbose_name='Funcionario')),
                ('vitima', models.ForeignKey(help_text='Nome da vitima', on_delete=django.db.models.deletion.PROTECT, to='vitima.vitima', verbose_name='Vitima')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
    ]
