# Generated by Django 5.1.2 on 2024-11-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.DecimalField(decimal_places=2, help_text='unidade de items do chamado', max_digits=5, verbose_name='unidade')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='quantidade do produtos em estoque', max_digits=5, verbose_name='Quantidade')),
                ('prioridade', models.TextField(help_text='Nivel de urgencia do chamado', max_length=300, verbose_name='Prioridade')),
                ('situacao', models.TextField(help_text='Estado do chamado', max_length=300, verbose_name='Situacao')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
    ]
