# Generated by Django 5.1.2 on 2024-12-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
        ('produtos', '0002_alter_produtos_tipo_de_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='produto',
            field=models.ForeignKey(blank=True, help_text='Produto a ser solicitado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produtos', verbose_name='Produto'),
        ),
    ]
