# Generated by Django 5.1.2 on 2024-11-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
        ('produtos', '0003_alter_produtos_tipo_de_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='produto',
            field=models.ForeignKey(default=4, help_text='Produto a ser solicitado', on_delete=django.db.models.deletion.PROTECT, to='produtos.produtos', verbose_name='Produto'),
            preserve_default=False,
        ),
    ]
