# Generated by Django 5.1.2 on 2024-12-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_alter_chamado_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-prioridade'], 'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
    ]
