# Generated by Django 5.1.2 on 2024-11-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do produto', max_length=100, unique=True, verbose_name='Nome')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='quantidade do produtos em estoque', max_digits=5, verbose_name='quantidade')),
                ('descricao', models.TextField(help_text='Descricao e observações do produto', max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
