# Generated by Django 5.1.2 on 2024-11-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tipo_de_produto',
            field=models.CharField(choices=[('MANTIMENTO', 'MANTIMENTO'), ('REMEDIO', 'REMEDIO'), ('ROUPA', 'ROUPA')], default=1, help_text='Tipo de mantimento ', max_length=10, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
