# Generated by Django 5.1.2 on 2024-12-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tipo_de_produto',
            field=models.CharField(blank=True, help_text='Tipo de produto', max_length=10, verbose_name='Tipo'),
        ),
    ]
