# Generated by Django 5.1.2 on 2024-11-04 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantimento',
            fields=[
                ('produtos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produtos')),
                ('validade', models.CharField(help_text='Validade do mantimento.', max_length=100, verbose_name='Validade')),
                ('categoria', models.CharField(help_text='Categoria do mantimento  (liquido ou solido ).', max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'mantimento',
                'verbose_name_plural': 'mantimentos',
            },
            bases=('produtos.produtos',),
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('produtos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produtos')),
                ('validade', models.CharField(help_text='Validade do remedio.', max_length=100, verbose_name='Validade')),
            ],
            options={
                'verbose_name': 'remedio',
                'verbose_name_plural': 'remedios',
            },
            bases=('produtos.produtos',),
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('produtos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produtos')),
                ('genero', models.CharField(help_text='masculino ou feminino.', max_length=100, verbose_name='Genero')),
                ('tamanho', models.CharField(help_text='tamanho da peça.', max_length=100, verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'roupa',
                'verbose_name_plural': 'roupas',
            },
            bases=('produtos.produtos',),
        ),
    ]
