# Generated by Django 5.1.2 on 2024-12-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtos_tipo_de_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedio',
            name='gramatura',
            field=models.IntegerField(default=1, help_text='Gramas do remedio', max_length=5, verbose_name='Gramatura'),
            preserve_default=False,
        ),
    ]
