# Generated by Django 5.1.2 on 2024-11-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtos_tipo_de_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tipo_de_produto',
            field=models.CharField(choices=[('MANTIMENTO', 'MANTIMENTO'), ('REMEDIO', 'REMEDIO'), ('ROUPA', 'ROUPA')], help_text='Tipo de produto', max_length=10, verbose_name='Tipo'),
        ),
    ]
