# Generated by Django 5.1.2 on 2024-12-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remedio_gramatura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantimento',
            options={'ordering': ['validade'], 'verbose_name': 'mantimento', 'verbose_name_plural': 'mantimentos'},
        ),
        migrations.AlterModelOptions(
            name='remedio',
            options={'ordering': ['validade'], 'verbose_name': 'remedio', 'verbose_name_plural': 'remedios'},
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(help_text='quantidade do produtos em estoque', verbose_name='quantidade'),
        ),
    ]
