# Generated by Django 5.1.2 on 2024-12-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_mantimento_options_alter_remedio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantimento',
            options={'ordering': ['-validade'], 'verbose_name': 'mantimento', 'verbose_name_plural': 'mantimentos'},
        ),
        migrations.AlterModelOptions(
            name='remedio',
            options={'ordering': ['-validade'], 'verbose_name': 'remedio', 'verbose_name_plural': 'remedios'},
        ),
    ]
