# Generated by Django 5.1.2 on 2024-12-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_mantimento_options_alter_remedio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantimento',
            options={'ordering': ['validade'], 'verbose_name': 'mantimento', 'verbose_name_plural': 'mantimentos'},
        ),
    ]
