# Generated by Django 5.1.2 on 2024-12-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_mantimento_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantimento',
            name='validade',
            field=models.IntegerField(help_text='Validade do mantimento.', max_length=100, verbose_name='Validade'),
        ),
    ]
