# Generated by Django 5.1.2 on 2024-12-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_mantimento_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remedio',
            name='validade',
            field=models.IntegerField(help_text='Validade do remedio.', max_length=100, verbose_name='Validade'),
        ),
    ]
