# Generated by Django 5.1.2 on 2024-12-10 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_alter_remedio_validade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='mantimento',
            name='produtos_ptr',
        ),
        migrations.RemoveField(
            model_name='remedio',
            name='produtos_ptr',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='produtos_ptr',
        ),
        migrations.AlterField(
            model_name='mantimento',
            name='validade',
            field=models.CharField(help_text='Validade do mantimento.', max_length=100, verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='remedio',
            name='gramatura',
            field=models.CharField(help_text='Gramas do remedio', max_length=5, verbose_name='Gramatura'),
        ),
        migrations.AlterField(
            model_name='remedio',
            name='validade',
            field=models.CharField(help_text='Validade do remedio.', max_length=100, verbose_name='Validade'),
        ),
        migrations.CreateModel(
            name='ItemProdutos',
            fields=[
                ('produtos_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produtos')),
                ('quantidade', models.IntegerField(default=0, help_text='Quantidade do produto em estoque', verbose_name='Quantidade')),
            ],
            bases=('produtos.produtos',),
        ),
        migrations.AddField(
            model_name='mantimento',
            name='itemprodutos_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.itemprodutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedio',
            name='itemprodutos_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.itemprodutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roupa',
            name='itemprodutos_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.itemprodutos'),
            preserve_default=False,
        ),
    ]
