# Generated by Django 5.1.2 on 2024-12-10 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_remove_produtos_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantimento',
            name='itemprodutos_ptr',
        ),
        migrations.RemoveField(
            model_name='roupa',
            name='itemprodutos_ptr',
        ),
        migrations.RemoveField(
            model_name='remedio',
            name='itemprodutos_ptr',
        ),
        migrations.AlterModelOptions(
            name='mantimento',
            options={'ordering': ['validade'], 'verbose_name': 'Mantimento', 'verbose_name_plural': 'Mantimentos'},
        ),
        migrations.AlterModelOptions(
            name='remedio',
            options={'ordering': ['-validade'], 'verbose_name': 'Remédio', 'verbose_name_plural': 'Remédios'},
        ),
        migrations.AlterModelOptions(
            name='roupa',
            options={'verbose_name': 'Roupa', 'verbose_name_plural': 'Roupas'},
        ),
        migrations.AddField(
            model_name='mantimento',
            name='produtos_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mantimento',
            name='quantidade',
            field=models.IntegerField(default=0, help_text='Quantidade do produto em estoque', verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='remedio',
            name='produtos_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedio',
            name='quantidade',
            field=models.IntegerField(default=0, help_text='Quantidade do produto em estoque', verbose_name='Quantidade'),
        ),
        migrations.AddField(
            model_name='roupa',
            name='produtos_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produtos.produtos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roupa',
            name='quantidade',
            field=models.IntegerField(default=0, help_text='Quantidade do produto em estoque', verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='mantimento',
            name='categoria',
            field=models.CharField(help_text='Categoria do mantimento (líquido ou sólido).', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(help_text='Descrição e observações do produto', max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='remedio',
            name='gramatura',
            field=models.CharField(help_text='Gramas do remédio', max_length=5, verbose_name='Gramatura'),
        ),
        migrations.AlterField(
            model_name='remedio',
            name='validade',
            field=models.CharField(help_text='Validade do remédio.', max_length=100, verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='genero',
            field=models.CharField(help_text='Masculino ou feminino.', max_length=100, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='roupa',
            name='tamanho',
            field=models.CharField(help_text='Tamanho da peça.', max_length=100, verbose_name='Tamanho'),
        ),
        migrations.DeleteModel(
            name='ItemProdutos',
        ),
    ]
