# Generated by Django 5.1.2 on 2024-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_remove_mantimento_itemprodutos_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do produto', max_length=100, unique=True, verbose_name='Nome')),
                ('tipo_de_produto', models.CharField(blank=True, help_text='Tipo de produto', max_length=10, verbose_name='Tipo')),
            ],
        ),
    ]
