# Generated by Django 5.1.2 on 2024-12-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
        ('listaprodutos', '0001_initial'),
        ('produtos', '0012_delete_modelo_alter_produtos_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='produto',
            field=models.ManyToManyField(through='listaprodutos.ListaProdutos', to='produtos.produtos'),
        ),
    ]
